#!/bin/bash
set -euo pipefail

# Submit HCS sweep (generated by generate_hcs_sweep.py) as a SLURM array.
#
# Defaults:
#   cases file : runs/HCS/hcs_modeB_cases.txt
#   lammps bin : runs/HCS/lmp
#   input file : in.hcs
#
# Examples:
#   runs/HCS/submit_hcs_sweep.sh
#   runs/HCS/submit_hcs_sweep.sh runs/HCS/hcs_modeB_cases.txt /path/to/lmp in.hcs

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CASES_FILE="${1:-${SCRIPT_DIR}/hcs_modeB_cases.txt}"
LAMMPS_BIN="${2:-${SCRIPT_DIR}/lmp}"
INPUT_SCRIPT="${3:-in.hcs}"
JOB_SCRIPT="${SCRIPT_DIR}/../hpc_array_lammps_cases.sh"

CASES_FILE="$(realpath "$CASES_FILE")"
if [[ -e "$LAMMPS_BIN" ]]; then
    LAMMPS_BIN="$(realpath "$LAMMPS_BIN")"
fi

if [[ ! -f "$CASES_FILE" ]]; then
    echo "ERROR: cases file not found: $CASES_FILE"
    exit 2
fi

if [[ ! -x "$LAMMPS_BIN" ]]; then
    echo "ERROR: LAMMPS binary not executable: $LAMMPS_BIN"
    exit 2
fi

if [[ ! -f "$JOB_SCRIPT" ]]; then
    echo "ERROR: array job script not found: $JOB_SCRIPT"
    exit 2
fi

mkdir -p "${SCRIPT_DIR}/logs"

NCASES="$(grep -Ev '^[[:space:]]*(#|$)' "$CASES_FILE" | wc -l | awk '{print $1}')"
if [[ "$NCASES" -lt 1 ]]; then
    echo "ERROR: no cases found in $CASES_FILE"
    exit 2
fi

ARRAY_MAX=$((NCASES - 1))
echo "Submitting ${NCASES} HCS cases as array 0-${ARRAY_MAX}"
echo "Case list : $CASES_FILE"
echo "LAMMPS bin: $LAMMPS_BIN"
echo "Input file: $INPUT_SCRIPT"

sbatch \
  --chdir "$SCRIPT_DIR" \
  --array "0-${ARRAY_MAX}" \
  "$JOB_SCRIPT" \
  "$CASES_FILE" \
  "$LAMMPS_BIN" \
  "$INPUT_SCRIPT"
